# Generated by Django 3.2.7 on 2021-09-10 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercuryapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='employee_Id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='product_Id',
        ),
    ]
