# Generated by Django 3.2.7 on 2021-09-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercuryapi', '0002_auto_20210913_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('revenue', models.IntegerField()),
                ('profit', models.IntegerField()),
            ],
        ),
    ]
