# Generated by Django 3.2.7 on 2021-09-10 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercuryapi', '0002_auto_20210910_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mercuryapi.department'),
            preserve_default=False,
        ),
    ]
