# Generated by Django 3.2.7 on 2021-09-10 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercuryapi', '0003_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeschedule',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mercuryapi.employee'),
            preserve_default=False,
        ),
    ]
