# Generated by Django 3.2.7 on 2021-09-10 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercuryapi', '0004_employeeschedule_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mercuryapi.department'),
            preserve_default=False,
        ),
    ]
