# Generated by Django 3.2.7 on 2021-09-10 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercuryapi', '0005_product_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mercuryapi.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mercuryapi.product'),
            preserve_default=False,
        ),
    ]
